# Generated by Django 5.2.4 on 2025-07-30 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_product_options_alter_product_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='info',
            field=models.URLField(default=1, verbose_name='информация'),
            preserve_default=False,
        ),
    ]
