# Generated by Django 4.2 on 2025-08-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='info',
            field=models.URLField(blank=True, null=True, verbose_name='информация'),
        ),
    ]
